server/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/admin/sidekiq'

  get "/auth/:provider/callback" => "sns#oauth_callback"

  resource :sns, controller: :sns, only: [] do
    get :admin_index
  end

  resource :apk_downloader, controller: :apk_downloader, only: [] do
    get 'warakatsu'
    get 'citore'
  end

  resources :fey_kun, controller: :fey_kun, only: [] do
    member do
      get 'report'
    end

    collection do
      post 'analized'
    end
  end

  resource :variable_template, controller: :variable_template, only: [] do
    get 'warakatsu_apk_download'
    get 'citore_apk_download'
    get 'citore_movie'
    get 'citore_slide'
    get 'marionette_movie'
    get 'marionette_slide'
  end

  resources :wssample, controller: :wssample, only: [:index]

  namespace :sugarcoat do
    resource :bot, controller: :bot, only: [] do
      get 'speak'
      get 'callback'
      post 'callback'
      get 'linebot_callback'
      post 'linebot_callback'
    end

    resource :landing, controller: :landing, only: [] do
      get 'page'
      get 'page01'
      get 'page02'
      get 'page03'
    end
  end

  namespace :citore do
    resource :voice, controller: :voice, only: [] do
      get 'download'
    end

    resources :words, only: [:index] do
      collection do
        get 'search'
      end
    end
  end

  namespace :bots do
    resource :line, controller: :line, only: [] do
      get :sugarcoat
      post :sugarcoat
      get :citore
      post :citore
      get :spotgacha
      post :spotgacha
      get :job_with_life
      post :job_with_life
      get :shiritori
      post :shiritori
      get :mone
      post :mone
    end

    resource :facebook, controller: :facebook, only: [] do
      get :sugarcoat
      post :sugarcoat
      get :citore
      post :citore
      get :spotgacha
      post :spotgacha
      get :job_with_life
      post :job_with_life
      get :shiritori
      post :shiritori
      get :mone
      post :mone
    end

    resource :selection, controller: :selection, only: [] do
      get :spotgacha
    end
  end

  namespace :tools do
    root to: "top#index"

    resource :graphics, controller: :graphics, only: [] do
      get :canvas
      get :threed
      get :base64
    end

    resource :texture_packer, controller: :texture_packer, only: [] do
      get :index
      post :pack
    end

    resource :image_crawl, controller: :image_crawl, only: [] do
      get :index
      get :twitter
      post :twitter_crawl
      get :flickr
      post :flickr_crawl
      get :url
      post :url_crawl
      get :download_zip
      get :google_image_search
      post :google_image_search_crawl
      get :niconico
      post :niconico_crawl
      get :getty_images
      post :getty_images_crawl
    end

    resource :audio, controller: :audio, only: [] do
      get :index
      get :listen_from_spotify
      get :crawl
      get :crawl_website
      post :execute_crawl
    end

    resource :excel_converter, controller: :excel_converter, only: [] do
      get :index
      post :convert_to_json
    end

    resource :twitter, controller: :twitter, only: [] do
      get :index
      get :input_user
      post :only_follower_users
      post :only_following_users
      post :remove_followers
      post :crawl_user_all_tweet
    end

    resources :webrtcs, only: [:index] do
      collection do
        get :freedom_videochat
      end
    end

    resources :websockets, only: [:index] do
      collection do
        get :twitter_sample
      end
    end

    resources :threed_objects, only: [:index] do
      collection do
        get :sample
        get :editor
        get :download
      end
    end

    resource :video, controller: :video, only: [] do
      get :index
      get :editor
      post :edit
      get :crawl
      post :execute_crawl
    end
  end

  namespace :unibo do
    resource :talk, controller: :talk, only: [] do
      get :index
      get :input
      get :say
      post :say
    end
  end

  namespace :egaonotatsuzin do
    resource :authentication, controller: :authentication, only: [] do
      get :sign_in
      get :callback
    end

    namespace :api do
      resources :playlists, only: [:index] do
        collection do
          get :analysis
        end
      end
    end
  end

  namespace :hackathon do
    namespace :musichackday2018 do
      resource :authentication, controller: :authentication, only: [] do
        get :signin
        get :spotify_login
        get :callback
      end

      namespace :api do
        resource :location, controller: :location, only: [] do
          post :notify
        end
        resource :sound, controller: :sound, only: [] do
          get :search_one
          post :play
          post :play_next
          post :keep_remix
        end
      end

      root to: "top#index"
    end

    namespace :arstudio2017 do
      resource :loader, controller: :loader, only: [] do
        get :index
        get :upload_admin
        post :upload
        get :remove
        get :switcher_admin
        post :switch
      end
    end

    namespace :sunflower do
      resources :images, only: [:index] do
        collection do
          post :upload_ferry
          post :upload_target
          post :upload_image_resources
          get :composite
        end
      end
      resources :users, only: [] do
        collection do
          post :login
        end
      end
      resource :twillio, controller: :twillio, only: [] do
        post :reserve
      end
    end
  end

  namespace :bannosama do
    root to: "top#index"

    resources :photos, only: [:index] do
      collection do
        post :upload
      end
    end

    resource :convey, controller: :convey, only: [] do
      get :index
      get :proto
      get :upload_ng
      get :upload_phone
      get :upload_test
    end

    resources :greets, controller: :greets, only: [] do
      collection do
        get :list
        get :mode_change
      end

      member do
        get :receive
      end
    end
  end

  namespace :food_forecast do
    root to: "top#index"

    resource :top, controller: :top, only: [] do
      post :send_location
    end

    resource :auth, controller: :auth, only: [] do
      post :login
      post :logout
      post :signup
    end

    resources :settings, only: [] do
      collection do
        get :input
        post :register
      end
    end
  end

  scope module: :homepage do
    resource :profile, controller: :profile, only: [] do
      get :index
    end

    resources :products, only: [:index, :show]
    resources :relations, only: [:index]
    resources :articles, only: [:index]

    resource :contact, controller: :contact, only: [] do
      get :index
    end

    resource :top, controller: :top, only: [] do
      post :regist_visitor
    end

  end

  root to: "homepage/top#index"
end

server/app/controllers/homepage/tools/audio_controller.rb
class Homepage::Tools::AudioController < Homepage::BaseController
  before_action :check_and_auth_account, only: :listen_from_spotify
  before_action :execute_upload_job, only: :execute_crawl

  def index
  end

  def listen_from_spotify
  end

  def crawl
    if @visitor.blank?
      @upload_jobs = []
    else
      @upload_jobs = @visitor.upload_jobs.where.not(state: :cleaned).where(from_type: "Datapool::WebSiteAudioMetum").order("id DESC")
    end
  end

  def crawl_website
  end

  def execute_crawl
    redirect_to crawl_tools_audio_url
  end

  private
  def check_and_auth_account
    if @visitor.spotify.nil?
      session["redirect_url"] = listen_from_spotify_tools_audio_url
      session["user_id"] = @visitor.id
      session["user_type"] = @visitor.class.to_s
      redirect_to "/auth/spotify" and return
    end
  end

  def execute_upload_job
    if params["crawl_type"] == "website"
      prefix = "Datapool::WebSiteAudioMetum"
    else
      prefix = ""
    end
    @upload_job = @visitor.upload_jobs.find_or_initialize_by(token: params[:authenticity_token])
    @upload_job.from_type = prefix
    @upload_job.options ||= {params: params.to_h.dup}
    @upload_job.save!
    flash[:notice] = "処理を受け付けました。処理が完了するまでしばらくお待ち下さい。"
    AudioCrawlWorker.perform_async(params.to_h.dup, @upload_job.id)
  end
end

server/app/controllers/homepage/tools/excel_converter_controller.rb
class Homepage::Tools::ExcelConverterController < Homepage::BaseController
  def index
  end

  def convert_to_json
  end
end

server/app/controllers/homepage/tools/graphics_controller.rb
class Homepage::Tools::GraphicsController < Homepage::BaseController
  def canvas
  end

  def base64
    ime = ImageMetum.first
    render plain: ime.convert_to_base64
  end

  def threed
  end
end

server/app/controllers/homepage/tools/image_crawl_controller.rb
class Homepage::Tools::ImageCrawlController < Homepage::BaseController

  before_action :load_upload_jobs, only: :index
  before_action :execute_upload_job, only: [:url_crawl, :twitter_crawl, :flickr_crawl, :google_image_search_crawl, :niconico_crawl, :getty_images_crawl]

  def index
  end

  def twitter
  end

  def twitter_crawl
    redirect_to tools_image_crawl_url
  end

  def flickr
  end

  def flickr_crawl
    redirect_to tools_image_crawl_url
  end

  def url
  end

  def url_crawl
    redirect_to tools_image_crawl_url
  end

  def google_image_search
  end

  def google_image_search_crawl
    redirect_to tools_image_crawl_url
  end

  def niconico
  end

  def niconico_crawl
    redirect_to tools_image_crawl_url
  end

  def getty_images

  end

  def getty_images_crawl
    redirect_to tools_image_crawl_url
  end

  def download_zip
    job = @visitor.upload_jobs.find_by(id: params[:job_id])
    job.downloaded!
    redirect_to job.upload_url
  end

  private
  def check_and_auth_google
    if @visitor.google.nil?
      session["redirect_url"] = tools_image_crawl_url
      session["user_id"] = @visitor.id
      session["user_type"] = @visitor.class.to_s
      redirect_to "/auth/google_oauth2" and return
    end
  end

  def load_upload_jobs
    if @visitor.blank?
      @upload_jobs = []
    else
      @upload_jobs = @visitor.upload_jobs.where.not(state: :cleaned).
        where(from_type: ["Datapool::FrickrImageMetum", "Datapool::TwitterImageMetum", "Datapool::WebSiteImageMetum", "Datapool::GoogleImageSearch"]).
        order("id DESC")
    end
  end

  def execute_upload_job
    if params[:action] == "flickr_crawl"
      prefix = "Datapool::FrickrImageMetum"
    elsif params[:action] == "twitter_crawl"
      prefix = "Datapool::TwitterImageMetum"
    elsif params[:action] == "url_crawl"
      prefix = "Datapool::WebSiteImageMetum"
    elsif params[:action] == "niconico_crawl"
      prefix = "Datapool::NiconicoImageMetum"
    elsif params[:action] == "getty_images_crawl"
      prefix = "Datapool::GettyImageMetum"
    else
      prefix = "Datapool::GoogleImageSearch"
    end
    @upload_job = @visitor.upload_jobs.find_or_initialize_by(token: params[:authenticity_token])
    @upload_job.from_type = prefix
    @upload_job.options ||= {params: params.to_h.dup}
    @upload_job.save!
    flash[:notice] = "処理を受け付けました。処理が完了するまでしばらくお待ち下さい。"
    ImageCrawlWorker.perform_async(params.to_h.dup, @upload_job.id)
  end
end

server/app/controllers/homepage/tools/texture_packer_controller.rb
class Homepage::Tools::TexturePackerController < Homepage::BaseController
  def index
  end

  def pack
  end
end

server/app/controllers/homepage/tools/threed_objects_controller.rb
class Homepage::Tools::ThreedObjectsController < Homepage::BaseController
  def index
  end

  def sample
  end

  def editor
  end

  def download
    counter = ExtraInfo.read_extra_info["threed_object_donwload_sum"].to_i
    ExtraInfo.update({"threed_object_donwload_sum" => counter + 1})
    redirect_to "https://s3-ap-northeast-1.amazonaws.com/taptappun/for_send/threed_models/taku_model.zip"
  end
end

server/app/controllers/homepage/tools/top_controller.rb
class Homepage::Tools::TopController < Homepage::BaseController
  def index
    @tools = Homepage::Tool.page(params[:page]).per(10)
  end
end

server/app/controllers/homepage/tools/twitter_controller.rb
class Homepage::Tools::TwitterController < Homepage::BaseController
  before_action :load_twitter_client

  def index
  end

  def input_user
  end

  def only_follower_users
    following_ids = get_all_following_ids(params[:twitter_user].to_s)
    follower_ids = get_all_follower_ids(params[:twitter_user].to_s)
    only_following_ids = follower_ids - following_ids
    @twitter_users = []

    begin
      @twitter_users = only_following_ids.each_slice(100).to_a.inject([]) do |users, ids|
        users.concat(client.users(ids))
      end
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def only_following_users
    following_ids = get_all_following_ids(params[:twitter_user].to_s)
    follower_ids = get_all_follower_ids(params[:twitter_user].to_s)
    only_following_ids = following_ids - follower_ids
    @twitter_users = []

    begin
      @twitter_users = only_following_ids.each_slice(100).to_a.inject([]) do |users, ids|
        users.concat(client.users(ids))
      end
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def followers
    begin
      @twitter_client.follow(params[:follow_twitter_ids])
      flash[:notice] = "followしました"
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def remove_followers
    begin
      @twitter_client.unfollow(params[:remove_twitter_ids])
      flash[:notice] = "followをやめました"
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def crawl_user_all_tweet
    max_id = nil
    timeline_count = 200
    all_tweets = []
    tweets = []
    loop do
      options = {count: timeline_count, trim_user: true, exclude_replies: true, contributor_details: false, include_rts: false}
      if max_id.present?
        options.merge!({max_id: max_id.to_i - 1})
      end
      begin
        tweets = @twitter_client.user_timeline(params[:twitter_user].to_s, options)
        max_id = tweets.min_by{|t| t.id }.try(:id)
      rescue Twitter::Error::TooManyRequests => error
        tweets = []
        flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
        break
      end
      all_tweets << tweets
      #公開されていないtweetもあるので200件までにおさまるとは限らない
      break if tweets.size <= 0
    end

    if params[:is_file].present?
      download_file_name = Time.current.strftime("%Y%m%d_%H%M%S") + "_tweets.json"
      tempfile = Tempfile.new(download_file_name)
      tempfile.write(all_tweets.to_json)
      tempfile.close
      tempfile.unlink
      send_file tempfile.path, :filename => download_file_name
    else
      render :json => all_tweets.to_json
    end
  end

  private
  def load_twitter_client
    @twitter_client = TwitterRecord.get_twitter_rest_client("citore")
  end

  def get_all_follower_ids(twitter_user)
    all_follower_ids = []
    follower_ids = []
    loop do
      options = {count: 5000}
      begin
        follower_ids = client.follower_ids(twitter_user, options).to_a
      rescue Twitter::Error::TooManyRequests => error
        follower_ids = []
        flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
        break
      end
      all_follower_ids << follower_ids
      break if follower_ids.size <= 0
    end
    return all_follower_ids.flatten
  end

  def get_all_following_ids(twitter_user)
    all_following_ids = []
    following_ids = []
    loop do
      options = {count: 5000}
      begin
        following_ids = client.friend_ids(twitter_user, options).to_a
      rescue Twitter::Error::TooManyRequests => error
        following_ids = []
        flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
        break
      end
      all_following_ids << following_ids
      break if following_ids.size <= 0
    end
    return all_following_ids.flatten
  end
end

server/app/controllers/homepage/tools/video_controller.rb
class Homepage::Tools::VideoController < Homepage::BaseController
  def index
  end

  def editor
  end

  def edit
    video_url = params[:video_url]
    video_file = params[:video_file]
    upload_url = params[:upload_url]
  end

  def crawl
  end

  def execute_crawl
    redirect_to crawl_tools_video_url
  end
end

server/app/controllers/homepage/tools/webrtcs_controller.rb
class Homepage::Tools::WebrtcsController < Homepage::BaseController
  def index
  end

  def freedom_videochat
  end
end

server/app/controllers/homepage/tools/websockets_controller.rb
class Homepage::Tools::WebsocketsController < Homepage::BaseController
  def index
  end

  def twitter_sample
    render :layout => false
  end
end

server/app/views/homepage/tools/webrtcs/freedom_videochat.html.erb
<div>
  WebRTCについてなんか書いていく<br>
  <button type="button" onclick="startVideo();">Start Video</button>
  <button type="button" onclick="stopVideo();">Stop Video</button>
  <button type="button" onclick="connect();">Connect</button>
  <button type="button" onclick="hangUp();">Hang Up</button>
  <div>
    <video id="local_video" autoplay style="width: 160px; height: 120px; border: 1px solid black;"></video>
    <video id="remote_video" autoplay style="width: 160px; height: 120px; border: 1px solid black;"></video>
  </div>
  <p>SDP to send:<br />
    <textarea id="text_for_send_sdp" rows="5" cols="60" readonly="readonly">SDP to send</textarea>
  </p>
  <p>SDP to receive:<br />
    <textarea id="text_for_receive_sdp" rows="5" cols="60"></textarea>
  </p>
</div>
<script type="text/javascript">
  let localVideo = document.getElementById('local_video');
  let remoteVideo = document.getElementById('remote_video');
  let localStream = null;
  let peerConnection = null;
  let textForSendSdp = document.getElementById('text_for_send_sdp');
  let textToReceiveSdp = document.getElementById('text_for_receive_sdp');

  var localSdp = "";

  // Websocket
  var hostname = window.document.location.hostname;
  var port = 3110;
  var protocol = window.document.location.protocol;
  var url;
  var websocket_path = "webrtc";
  if(protocol.startsWith("https")){
    url = 'wss://' + hostname;
  }else{
    url = 'ws://' + hostname;
  }
  if(hostname.startsWith("localhost") || navigator.onLine){
    url = url + ":" + port;
  }
  url = url + "/streaming"
  var ws = new WebSocket(url);
  ws.onopen = function(event){
    ws.send(JSON.stringify({action: "connection", path: websocket_path}));
  }

  ws.onmessage = function (event) {
    if(localSdp.length > 0){
      var sdpMessage = JSON.parse(event.data);
      if(localSdp != sdpMessage.sdp){
        console.log("remote??");
        onSdpText(sdpMessage.sdp);
      }else{
        console.log("same!!");
      }
    }
  };

  // --- prefix -----
  var RTCPeerConnection = window.RTCPeerConnection || window.webkitRTCPeerConnection || window.mozRTCPeerConnection;
  var RTCSessionDescription = window.RTCSessionDescription || window.webkitRTCSessionDescription || window.mozRTCSessionDescription;


  // start local video
  function startVideo() {
    getDeviceStream({video: true, audio: false})
    .then(function (stream) { // success
      localStream = stream;
      playVideo(localVideo, stream);
    }).catch(function (error) { // error
      console.error('mediaDevice.getUserMedia() error:', error);
      return;
    });
  }

  // stop local video
  function stopVideo() {
    pauseVideo(localVideo);
    stopLocalStream(localStream);
    localSdp = "";
  }

  function stopLocalStream(stream) {
    let tracks = stream.getTracks();
    if (! tracks) {
      console.warn('NO tracks');
      return;
    }
    for (let track of tracks) {
      track.stop();
    }
  }

  // ---- 新旧APIをPromiseでラップする ----
  function getDeviceStream(option) {
    if ('getUserMedia' in navigator.mediaDevices) {
      console.log('navigator.mediaDevices.getUserMadia');
      return navigator.mediaDevices.getUserMedia(option);
    }
    else {
      console.log('wrap navigator.getUserMadia with Promise');
      return new Promise(function(resolve, reject){
        navigator.getUserMedia(option,
          resolve,
          reject
        );
      });
    }
  }

  function playVideo(element, stream) {
    if ('srcObject' in element) {
      element.srcObject = stream;
    } else {
      element.src = window.URL.createObjectURL(stream);
    }
    element.play();
    element.volume = 0;
  }

  function pauseVideo(element) {
    element.pause();
    if ('srcObject' in element) {
      element.srcObject = null;
    }
    else {
      if (element.src && (element.src !== '') ) {
        window.URL.revokeObjectURL(element.src);
      }
      element.src = '';
    }
  }

  // ----- hand signaling ----
  function onSdpText(text) {
    if (peerConnection) {
      console.log('Received answer text...');
      let answer = new RTCSessionDescription({
        type : 'answer',
        sdp : text,
      });
      setAnswer(answer);
    } else {
      console.log('Received offer text...');
      let offer = new RTCSessionDescription({
        type : 'offer',
        sdp : text,
      });
      setOffer(offer);
    }
    textToReceiveSdp.value ='';
  }

  function sendSdp(sessionDescription) {
    console.log('---sending sdp ---');
    console.log(sessionDescription);
    ws.send(JSON.stringify({action: "send", path: websocket_path, message: {sdp: sessionDescription.sdp}}));
    textForSendSdp.value = sessionDescription.sdp;
    localSdp = sessionDescription.sdp;
    textForSendSdp.focus();
    textForSendSdp.select();
  }
 
  // ---------------------- connection handling -----------------------
  function prepareNewConnection() {
    let pc_config = {"iceServers":[]};
    let peer = new RTCPeerConnection(pc_config);
    console.log('peer:' + peer);
 
    // --- on get remote stream ---
    // オブジェクトの中にontrackがあるかどうか
    if ('ontrack' in peer) {
      peer.ontrack = function(event) {
        console.log('-- peer.ontrack()' + event);
        let stream = event.streams[0];
        playVideo(remoteVideo, stream);
      };
    } else {
      peer.onaddstream = function(event) {
        console.log('-- peer.onaddstream()');
        let stream = event.stream;
        playVideo(remoteVideo, stream);
      };
    }
 
    // --- on get local ICE candidate
    peer.onicecandidate = function (evt) {
      if (evt.candidate) {
        console.log(evt.candidate);
 
        // Trickle ICE の場合は、ICE candidateを相手に送る
        // Vanilla ICE の場合には、何もしない
      } else {
        console.log('empty ice event');
 
        // Trickle ICE の場合は、何もしない
        // Vanilla ICE の場合には、ICE candidateを含んだSDPを相手に送る
        sendSdp(peer.localDescription);
      }
    };
 
    
    // -- add local stream --
    if (localStream) {
      console.log('Adding local stream...');
      peer.addStream(localStream);
    }
    else {
      console.warn('no local stream, but continue.');
    }
 
    return peer;
  }
 
  function makeOffer() {
    peerConnection = prepareNewConnection();
    peerConnection.createOffer()
    .then(function (sessionDescription) {
      console.log('createOffer() succsess in promise');
      return peerConnection.setLocalDescription(sessionDescription);
    }).then(function() {
      console.log('setLocalDescription() succsess in promise');
 
      // -- Trickle ICE の場合は、初期SDPを相手に送る -- 
      // -- Vanilla ICE の場合には、まだSDPは送らない --
      //sendSdp(peerConnection.localDescription);
    }).catch(function(err) {
      console.error(err);
    });
  }
 
  function setOffer(sessionDescription) {
    if (peerConnection) {
      console.error('peerConnection alreay exist!');
    }
    peerConnection = prepareNewConnection();
    peerConnection.setRemoteDescription(sessionDescription)
    .then(function() {
      console.log('setRemoteDescription(offer) succsess in promise');
      makeAnswer();
    }).catch(function(err) {
      console.error('setRemoteDescription(offer) ERROR: ', err);
    });
  }
  
  function makeAnswer() {
    console.log('sending Answer. Creating remote session description...' );
    if (! peerConnection) {
      console.error('peerConnection NOT exist!');
      return;
    }
    
    peerConnection.createAnswer()
    .then(function (sessionDescription) {
      console.log('createAnswer() succsess in promise');
      return peerConnection.setLocalDescription(sessionDescription);
    }).then(function() {
      console.log('setLocalDescription() succsess in promise');
 
      // -- Trickle ICE の場合は、初期SDPを相手に送る -- 
      // -- Vanilla ICE の場合には、まだSDPは送らない --
      //sendSdp(peerConnection.localDescription);
    }).catch(function(err) {
      console.error(err);
    });
  }
 
  function setAnswer(sessionDescription) {
    if (! peerConnection) {
      console.error('peerConnection NOT exist!');
      return;
    }
 
    peerConnection.setRemoteDescription(sessionDescription)
    .then(function() {
      console.log('setRemoteDescription(answer) succsess in promise');
    }).catch(function(err) {
      console.error('setRemoteDescription(answer) ERROR: ', err);
    });
  }
  
  // start PeerConnection
  function connect() {
    if (!peerConnection) {
      console.log('make Offer');
      makeOffer();
    } else {
      console.warn('peer already exist.');
    }
  }
 
  // close PeerConnection
  function hangUp() {
    if (peerConnection) {
      console.log('Hang up.');
      peerConnection.close();
      peerConnection = null;
      localSdp = "";
      pauseVideo(remoteVideo);
    } else {
      console.warn('peer NOT exist.');
    }
  }
</script>

server/app/views/homepage/tools/webrtcs/index.html.erb
<div class="pure-g">
  <div class="pure-u-1-3">
    <p>とりあえず適当に誰か繋がる人がいたらビデオチャットにつながるかもしれません</p><br>
    <p><%= link_to("見てみる", freedom_videochat_tools_webrtcs_url) %></p>
  </div>
</div>