server/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/admin/sidekiq'

  get "/auth/:provider/callback" => "sns#oauth_callback"

  resource :sns, controller: :sns, only: [] do
    get :admin_index
  end

  resource :apk_downloader, controller: :apk_downloader, only: [] do
    get 'warakatsu'
    get 'citore'
  end

  resources :fey_kun, controller: :fey_kun, only: [] do
    member do
      get 'report'
    end

    collection do
      post 'analized'
    end
  end

  resource :variable_template, controller: :variable_template, only: [] do
    get 'warakatsu_apk_download'
    get 'citore_apk_download'
    get 'citore_movie'
    get 'citore_slide'
    get 'marionette_movie'
    get 'marionette_slide'
  end

  resources :wssample, controller: :wssample, only: [:index]

  namespace :sugarcoat do
    resource :bot, controller: :bot, only: [] do
      get 'speak'
      get 'callback'
      post 'callback'
      get 'linebot_callback'
      post 'linebot_callback'
    end

    resource :landing, controller: :landing, only: [] do
      get 'page'
      get 'page01'
      get 'page02'
      get 'page03'
    end
  end

  namespace :citore do
    resource :voice, controller: :voice, only: [] do
      get 'download'
    end

    resources :words, only: [:index] do
      collection do
        get 'search'
      end
    end
  end

  namespace :bots do
    resource :line, controller: :line, only: [] do
      get :sugarcoat
      post :sugarcoat
      get :citore
      post :citore
      get :spotgacha
      post :spotgacha
      get :job_with_life
      post :job_with_life
      get :shiritori
      post :shiritori
      get :mone
      post :mone
    end

    resource :facebook, controller: :facebook, only: [] do
      get :sugarcoat
      post :sugarcoat
      get :citore
      post :citore
      get :spotgacha
      post :spotgacha
      get :job_with_life
      post :job_with_life
      get :shiritori
      post :shiritori
      get :mone
      post :mone
    end

    resource :selection, controller: :selection, only: [] do
      get :spotgacha
    end
  end

  namespace :tools do
    root to: "top#index"

    resource :graphics, controller: :graphics, only: [] do
      get :canvas
      get :threed
      get :base64
    end

    resource :texture_packer, controller: :texture_packer, only: [] do
      get :index
      post :pack
    end

    resource :image_crawl, controller: :image_crawl, only: [] do
      get :index
      get :twitter
      post :twitter_crawl
      get :flickr
      post :flickr_crawl
      get :url
      post :url_crawl
      get :download_zip
      get :google_image_search
      post :google_image_search_crawl
      get :niconico
      post :niconico_crawl
      get :getty_images
      post :getty_images_crawl
    end

    resource :audio, controller: :audio, only: [] do
      get :index
      get :listen_from_spotify
      get :crawl
      get :crawl_website
      post :execute_crawl
    end

    resource :excel_converter, controller: :excel_converter, only: [] do
      get :index
      post :convert_to_json
    end

    resource :twitter, controller: :twitter, only: [] do
      get :index
      get :input_user
      post :only_follower_users
      post :only_following_users
      post :remove_followers
      post :crawl_user_all_tweet
    end

    resources :webrtcs, only: [:index] do
      collection do
        get :freedom_videochat
      end
    end

    resources :websockets, only: [:index] do
      collection do
        get :twitter_sample
      end
    end

    resources :threed_objects, only: [:index] do
      collection do
        get :sample
        get :editor
        get :download
      end
    end

    resource :video, controller: :video, only: [] do
      get :index
      get :editor
      post :edit
      get :crawl
      post :execute_crawl
    end
  end

  namespace :unibo do
    resource :talk, controller: :talk, only: [] do
      get :index
      get :input
      get :say
      post :say
    end
  end

  namespace :egaonotatsuzin do
    resource :authentication, controller: :authentication, only: [] do
      get :sign_in
      get :callback
    end

    namespace :api do
      resources :playlists, only: [:index] do
        collection do
          get :analysis
        end
      end
    end
  end

  namespace :hackathon do
    namespace :musichackday2018 do
      resource :authentication, controller: :authentication, only: [] do
        get :signin
        get :spotify_login
        get :callback
      end

      namespace :api do
        resource :location, controller: :location, only: [] do
          post :notify
        end
        resource :sound, controller: :sound, only: [] do
          get :search_one
          post :play
          post :play_next
          post :keep_remix
        end
      end

      root to: "top#index"
    end

    namespace :arstudio2017 do
      resource :loader, controller: :loader, only: [] do
        get :index
        get :upload_admin
        post :upload
        get :remove
        get :switcher_admin
        post :switch
      end
    end

    namespace :sunflower do
      resources :images, only: [:index] do
        collection do
          post :upload_ferry
          post :upload_target
          post :upload_image_resources
          get :composite
        end
      end
      resources :users, only: [] do
        collection do
          post :login
        end
      end
      resource :twillio, controller: :twillio, only: [] do
        post :reserve
      end
    end
  end

  namespace :bannosama do
    root to: "top#index"

    resources :photos, only: [:index] do
      collection do
        post :upload
      end
    end

    resource :convey, controller: :convey, only: [] do
      get :index
      get :proto
      get :upload_ng
      get :upload_phone
      get :upload_test
    end

    resources :greets, controller: :greets, only: [] do
      collection do
        get :list
        get :mode_change
      end

      member do
        get :receive
      end
    end
  end

  namespace :food_forecast do
    root to: "top#index"

    resource :top, controller: :top, only: [] do
      post :send_location
    end

    resource :auth, controller: :auth, only: [] do
      post :login
      post :logout
      post :signup
    end

    resources :settings, only: [] do
      collection do
        get :input
        post :register
      end
    end
  end

  scope module: :homepage do
    resource :profile, controller: :profile, only: [] do
      get :index
    end

    resources :products, only: [:index, :show]
    resources :relations, only: [:index]
    resources :articles, only: [:index]

    resource :contact, controller: :contact, only: [] do
      get :index
    end

    resource :top, controller: :top, only: [] do
      post :regist_visitor
    end

  end

  root to: "homepage/top#index"
end

server/app/controllers/homepage/tools/audio_controller.rb
class Homepage::Tools::AudioController < Homepage::BaseController
  before_action :check_and_auth_account, only: :listen_from_spotify
  before_action :execute_upload_job, only: :execute_crawl

  def index
  end

  def listen_from_spotify
  end

  def crawl
    if @visitor.blank?
      @upload_jobs = []
    else
      @upload_jobs = @visitor.upload_jobs.where.not(state: :cleaned).where(from_type: "Datapool::WebSiteAudioMetum").order("id DESC")
    end
  end

  def crawl_website
  end

  def execute_crawl
    redirect_to crawl_tools_audio_url
  end

  private
  def check_and_auth_account
    if @visitor.spotify.nil?
      session["redirect_url"] = listen_from_spotify_tools_audio_url
      session["user_id"] = @visitor.id
      session["user_type"] = @visitor.class.to_s
      redirect_to "/auth/spotify" and return
    end
  end

  def execute_upload_job
    if params["crawl_type"] == "website"
      prefix = "Datapool::WebSiteAudioMetum"
    else
      prefix = ""
    end
    @upload_job = @visitor.upload_jobs.find_or_initialize_by(token: params[:authenticity_token])
    @upload_job.from_type = prefix
    @upload_job.options ||= {params: params.to_h.dup}
    @upload_job.save!
    flash[:notice] = "処理を受け付けました。処理が完了するまでしばらくお待ち下さい。"
    AudioCrawlWorker.perform_async(params.to_h.dup, @upload_job.id)
  end
end

server/app/controllers/homepage/tools/excel_converter_controller.rb
class Homepage::Tools::ExcelConverterController < Homepage::BaseController
  def index
  end

  def convert_to_json
  end
end

server/app/controllers/homepage/tools/graphics_controller.rb
class Homepage::Tools::GraphicsController < Homepage::BaseController
  def canvas
  end

  def base64
    ime = ImageMetum.first
    render plain: ime.convert_to_base64
  end

  def threed
  end
end

server/app/controllers/homepage/tools/image_crawl_controller.rb
class Homepage::Tools::ImageCrawlController < Homepage::BaseController

  before_action :load_upload_jobs, only: :index
  before_action :execute_upload_job, only: [:url_crawl, :twitter_crawl, :flickr_crawl, :google_image_search_crawl, :niconico_crawl, :getty_images_crawl]

  def index
  end

  def twitter
  end

  def twitter_crawl
    redirect_to tools_image_crawl_url
  end

  def flickr
  end

  def flickr_crawl
    redirect_to tools_image_crawl_url
  end

  def url
  end

  def url_crawl
    redirect_to tools_image_crawl_url
  end

  def google_image_search
  end

  def google_image_search_crawl
    redirect_to tools_image_crawl_url
  end

  def niconico
  end

  def niconico_crawl
    redirect_to tools_image_crawl_url
  end

  def getty_images

  end

  def getty_images_crawl
    redirect_to tools_image_crawl_url
  end

  def download_zip
    job = @visitor.upload_jobs.find_by(id: params[:job_id])
    job.downloaded!
    redirect_to job.upload_url
  end

  private
  def check_and_auth_google
    if @visitor.google.nil?
      session["redirect_url"] = tools_image_crawl_url
      session["user_id"] = @visitor.id
      session["user_type"] = @visitor.class.to_s
      redirect_to "/auth/google_oauth2" and return
    end
  end

  def load_upload_jobs
    if @visitor.blank?
      @upload_jobs = []
    else
      @upload_jobs = @visitor.upload_jobs.where.not(state: :cleaned).
        where(from_type: ["Datapool::FrickrImageMetum", "Datapool::TwitterImageMetum", "Datapool::WebSiteImageMetum", "Datapool::GoogleImageSearch"]).
        order("id DESC")
    end
  end

  def execute_upload_job
    if params[:action] == "flickr_crawl"
      prefix = "Datapool::FrickrImageMetum"
    elsif params[:action] == "twitter_crawl"
      prefix = "Datapool::TwitterImageMetum"
    elsif params[:action] == "url_crawl"
      prefix = "Datapool::WebSiteImageMetum"
    elsif params[:action] == "niconico_crawl"
      prefix = "Datapool::NiconicoImageMetum"
    elsif params[:action] == "getty_images_crawl"
      prefix = "Datapool::GettyImageMetum"
    else
      prefix = "Datapool::GoogleImageSearch"
    end
    @upload_job = @visitor.upload_jobs.find_or_initialize_by(token: params[:authenticity_token])
    @upload_job.from_type = prefix
    @upload_job.options ||= {params: params.to_h.dup}
    @upload_job.save!
    flash[:notice] = "処理を受け付けました。処理が完了するまでしばらくお待ち下さい。"
    ImageCrawlWorker.perform_async(params.to_h.dup, @upload_job.id)
  end
end

server/app/controllers/homepage/tools/texture_packer_controller.rb
class Homepage::Tools::TexturePackerController < Homepage::BaseController
  def index
  end

  def pack
  end
end

server/app/controllers/homepage/tools/threed_objects_controller.rb
class Homepage::Tools::ThreedObjectsController < Homepage::BaseController
  def index
  end

  def sample
  end

  def editor
  end

  def download
    counter = ExtraInfo.read_extra_info["threed_object_donwload_sum"].to_i
    ExtraInfo.update({"threed_object_donwload_sum" => counter + 1})
    redirect_to "https://s3-ap-northeast-1.amazonaws.com/taptappun/for_send/threed_models/taku_model.zip"
  end
end

server/app/controllers/homepage/tools/top_controller.rb
class Homepage::Tools::TopController < Homepage::BaseController
  def index
    @tools = Homepage::Tool.page(params[:page]).per(10)
  end
end

server/app/controllers/homepage/tools/twitter_controller.rb
class Homepage::Tools::TwitterController < Homepage::BaseController
  before_action :load_twitter_client

  def index
  end

  def input_user
  end

  def only_follower_users
    following_ids = get_all_following_ids(params[:twitter_user].to_s)
    follower_ids = get_all_follower_ids(params[:twitter_user].to_s)
    only_following_ids = follower_ids - following_ids
    @twitter_users = []

    begin
      @twitter_users = only_following_ids.each_slice(100).to_a.inject([]) do |users, ids|
        users.concat(client.users(ids))
      end
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def only_following_users
    following_ids = get_all_following_ids(params[:twitter_user].to_s)
    follower_ids = get_all_follower_ids(params[:twitter_user].to_s)
    only_following_ids = following_ids - follower_ids
    @twitter_users = []

    begin
      @twitter_users = only_following_ids.each_slice(100).to_a.inject([]) do |users, ids|
        users.concat(client.users(ids))
      end
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def followers
    begin
      @twitter_client.follow(params[:follow_twitter_ids])
      flash[:notice] = "followしました"
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def remove_followers
    begin
      @twitter_client.unfollow(params[:remove_twitter_ids])
      flash[:notice] = "followをやめました"
    rescue Twitter::Error::TooManyRequests => error
      flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
    end
  end

  def crawl_user_all_tweet
    max_id = nil
    timeline_count = 200
    all_tweets = []
    tweets = []
    loop do
      options = {count: timeline_count, trim_user: true, exclude_replies: true, contributor_details: false, include_rts: false}
      if max_id.present?
        options.merge!({max_id: max_id.to_i - 1})
      end
      begin
        tweets = @twitter_client.user_timeline(params[:twitter_user].to_s, options)
        max_id = tweets.min_by{|t| t.id }.try(:id)
      rescue Twitter::Error::TooManyRequests => error
        tweets = []
        flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
        break
      end
      all_tweets << tweets
      #公開されていないtweetもあるので200件までにおさまるとは限らない
      break if tweets.size <= 0
    end

    if params[:is_file].present?
      download_file_name = Time.current.strftime("%Y%m%d_%H%M%S") + "_tweets.json"
      tempfile = Tempfile.new(download_file_name)
      tempfile.write(all_tweets.to_json)
      tempfile.close
      tempfile.unlink
      send_file tempfile.path, :filename => download_file_name
    else
      render :json => all_tweets.to_json
    end
  end

  private
  def load_twitter_client
    @twitter_client = TwitterRecord.get_twitter_rest_client("citore")
  end

  def get_all_follower_ids(twitter_user)
    all_follower_ids = []
    follower_ids = []
    loop do
      options = {count: 5000}
      begin
        follower_ids = client.follower_ids(twitter_user, options).to_a
      rescue Twitter::Error::TooManyRequests => error
        follower_ids = []
        flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
        break
      end
      all_follower_ids << follower_ids
      break if follower_ids.size <= 0
    end
    return all_follower_ids.flatten
  end

  def get_all_following_ids(twitter_user)
    all_following_ids = []
    following_ids = []
    loop do
      options = {count: 5000}
      begin
        following_ids = client.friend_ids(twitter_user, options).to_a
      rescue Twitter::Error::TooManyRequests => error
        following_ids = []
        flash[:error] = "twitter apiの利用上限数を超えました。#{error.rate_limit.reset_in.to_i}秒経ってから再度ご利用ください。"
        break
      end
      all_following_ids << following_ids
      break if following_ids.size <= 0
    end
    return all_following_ids.flatten
  end
end

server/app/controllers/homepage/tools/video_controller.rb
class Homepage::Tools::VideoController < Homepage::BaseController
  def index
  end

  def editor
  end

  def edit
    video_url = params[:video_url]
    video_file = params[:video_file]
    upload_url = params[:upload_url]
  end

  def crawl
  end

  def execute_crawl
    redirect_to crawl_tools_video_url
  end
end

server/app/controllers/homepage/tools/webrtcs_controller.rb
class Homepage::Tools::WebrtcsController < Homepage::BaseController
  def index
  end

  def freedom_videochat
  end
end

server/app/controllers/homepage/tools/websockets_controller.rb
class Homepage::Tools::WebsocketsController < Homepage::BaseController
  def index
  end

  def twitter_sample
    render :layout => false
  end
end

server/app/views/homepage/tools/image_crawl/flickr.html.erb
<%= link_to("https://flickr.com", class: "logo_link") do %>
  <p><%= image_tag("icon/flickr_logo.png", size: "128x39") %></p>
  <p><b>Flickr</b></p>
<% end %>
<%= form_tag(flickr_crawl_tools_image_crawl_url, multipart: true, class: "pure-form pure-form-aligned") do %>
  <div class="pure-control-group">
    <%= label_tag("検索種別") %>
    <%= select_tag(:search_type, options_for_select(["フリーワード", "タグ名"].map.with_index{|word, i| [word.to_s, i] }), class: "pure-input-1-4") %>
  </div>
  <div class="pure-control-group">
    <%= label_tag("キーワード") %>
    <%= text_field_tag :keyword, "", placeholder: "keyword", class: "pure-input-2-3" %>
  </div>
  <div class="pure-controls">
    <%= submit_tag("画像をダウンロードする", class: "pure-button pure-button-primary") %>
  </div>
<% end %>

server/app/views/homepage/tools/image_crawl/getty_images.html.erb
<%= link_to("http://www.gettyimages.co.jp/", class: "logo_link") do %>
  <p><%= image_tag("icon/getty_images_logo.jpg", size: "128x23") %></p>
  <p><b>gettyimages</b></p>
<% end %>
<%= form_tag(getty_images_crawl_tools_image_crawl_url, multipart: true, class: "pure-form pure-form-aligned") do %>
  <div class="pure-control-group">
    <%= label_tag("キーワード") %>
    <%= text_field_tag :keyword, "", placeholder: "検索したい文字列を入力してください", class: "pure-input-2-3" %>
  </div>
  <div class="pure-controls">
    <%= submit_tag("画像をダウンロードする", class: "pure-button pure-button-primary") %>
  </div>
<% end %>

server/app/views/homepage/tools/image_crawl/google_image_search.html.erb
<%= link_to("https://www.google.co.jp/imghp", class: "logo_link") do %>
  <p><%= image_tag("icon/google_logo.png", size: "128x44") %></p>
  <p><b>Google画像検索</b></p>
<% end %>
<%= form_tag(google_image_search_crawl_tools_image_crawl_url, multipart: true, class: "pure-form pure-form-aligned") do %>
  <div class="pure-control-group">
    <%= label_tag("キーワード") %>
    <%= text_field_tag :keyword, "", placeholder: "検索したい文字列を入力してください", class: "pure-input-2-3" %>
  </div>
  <div class="pure-controls">
    <%= submit_tag("画像をダウンロードする", class: "pure-button pure-button-primary") %>
  </div>
<% end %>

server/app/views/homepage/tools/image_crawl/index.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key.to_s) %>
<% end %>

<h2>画像を収集したいサービスを選んでください</h2>
<div class="pure-g">
  <div class="pure-u-1">
    <%= link_to("Google画像検索から画像を収集(Beta)", google_image_search_tools_image_crawl_url) %>
  </div>
  <div class="pure-u-1">
    <%= link_to("Webサイトから画像を収集", url_tools_image_crawl_url) %>
  </div>
  <br>
  <div class="pure-u-1">
    <%= link_to("Twitterから画像を収集", twitter_tools_image_crawl_url) %>
  </div>
  <br>
  <div class="pure-u-1">
    <%= link_to("Flickrから画像を収集", flickr_tools_image_crawl_url) %>
  </div>
  <div class="pure-u-1">
    <%= link_to("ニコニコ静画(イラスト)から画像を収集", niconico_tools_image_crawl_url) %>
  </div>
  <div class="pure-u-1">
    <%= link_to("getty-imagesから画像を収集", getty_images_tools_image_crawl_url) %>
  </div>
</div>
<hr>
<h2>画像の収集状況</h2>
<div class="pure-g">
  <div class="pure-u-1">【注意】</div>
  <div class="pure-u-1">1.収集処理は順番に実行されます</div>
  <div class="pure-u-1">2.収集完了状態から1週間経過するとリストからなくなります。</div>
  <div class="pure-u-1">3.ダウンロードが完了した場合、1日経過するとリストからなくなります</div>
  <div class="pure-u-1">4.収集中状態から1日経過した場合もリストからなくなります</div>
</div>
<% if @upload_jobs.present? %>
  <table class="pure-table">
    <thead>
      <tr>
        <th>作成日時</th>
        <th>収集先</th>
        <th>状態</th>
        <th>ダウンロード</th>
      </tr>
    </thead>
    <tbody>
      <% @upload_jobs.each do |job| %>
        <tr>
          <td><%= job.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
          <td><%= job.from_type_name %></td>
          <%
            if job.downloaded?
              stylecolor = "drakgray"
            elsif job.failed?
              stylecolor = "crimson"
            elsif job.complete?
              stylecolor = "blue"
            else
              stylecolor = "forestgreen"
            end
          %>
          <td><span style="color:<%= stylecolor %>"><%= t("activerecord.enum.homepage_upload_job_queues.state.#{job.state}") %></span></td>
          <td><%=
            if job.upload_url.present?
              link_to("ダウンロード", download_zip_tools_image_crawl_url(job_id: job.id), class: "pure-button pure-button-primary")
            else
              ""
            end
          %></td>
        </tr>
      <% end %>
    </tbody>
  <table>
<% end %>

server/app/views/homepage/tools/image_crawl/niconico.html.erb
<%= link_to("http://seiga.nicovideo.jp/", class: "logo_link") do %>
  <p><%= image_tag("icon/seiga_logo.gif", size: "128x40") %></p>
  <p><b>ニコニコ静画(イラスト)</b></p>
<% end %>
<%= form_tag(niconico_crawl_tools_image_crawl_url, multipart: true, class: "pure-form pure-form-aligned") do %>
  <div class="pure-control-group">
    <%= label_tag("キーワード") %>
    <%= text_field_tag :keyword, "", placeholder: "検索したい文字列を入力してください", class: "pure-input-2-3" %>
  </div>
  <div class="pure-controls">
    <%= submit_tag("画像をダウンロードする", class: "pure-button pure-button-primary") %>
  </div>
<% end %>

server/app/views/homepage/tools/image_crawl/twitter.html.erb
<%= link_to("https://twitter.com", class: "logo_link") do %>
  <p><%= image_tag("icon/twitter_logo.png", size: "64x64") %></p>
  <p><b>Twitter</b></p>
<% end %>
<%= form_tag(twitter_crawl_tools_image_crawl_url, multipart: true, class: "pure-form pure-form-aligned") do %>
  <div class="pure-control-group">
    <%= label_tag("検索種別") %>
    <%= select_tag(:search_type, options_for_select(["フリーワード", "ユーザー名"].map.with_index{|word, i| [word.to_s, i] }), class: "pure-input-1-4") %>
  </div>
  <div class="pure-control-group">
    <%= label_tag("キーワード") %>
    <%= text_field_tag :keyword, "", placeholder: "検索したい文字列を入力してください", class: "pure-input-2-3" %>
  </div>
  <div class="pure-controls">
    <%= submit_tag("画像をダウンロードする", class: "pure-button pure-button-primary") %>
  </div>
<% end %>

server/app/views/homepage/tools/image_crawl/url.html.erb
<%= form_tag(url_crawl_tools_image_crawl_url, multipart: true, class: "pure-form pure-form-aligned") do %>
  <div class="pure-control-group">
    <%= label_tag("url") %>
    <%= text_field_tag :crawl_url, "", placeholder: "urlを入力してください", class: "pure-input-2-3" %>
  </div>
  <div class="pure-control-group">
    <%= label_tag("") %>
    <span>※繰り返し処理を行いたい場合は以下に指定してURLパラメータを基に繰り替えし処理を行います</span>
  </div>
  <div class="pure-control-group">
    <%= label_tag("絞りこみDOM要素") %>
    <%= text_field_tag :filter, "" ,class: "pure-input-2-3" %>
  </div>
  <div class="pure-control-group">
    <%= label_tag("") %>
    <span>classならば.class, idならば#idのように入力してください。</span>
  </div>
  <div class="pure-control-group">
    <%= label_tag("繰り返すパラメータキー") %>
    <%= text_field_tag :page_key, "" ,class: "pure-input-2-3" %>
  </div>
  <div class="pure-control-group">
    <%= label_tag("") %>
  </div>
  <div class="pure-control-group">
    <%= label_tag("繰り返す範囲") %>
    <%= number_field_tag :start_page_num %> ~ <%= number_field_tag :end_page_num %>
  </div>
  <div class="pure-controls">
    <%= submit_tag("画像を集める", class: "pure-button pure-button-primary") %>
  </div>
<% end %>
<hr>
<h4>入力例</h4>
<table class="pure-table">
  <tbody>
    <tr>
      <td>URL</td>
      <td><%= url_tools_image_crawl_url %></td>
    </tr>
    <tr>
      <td>繰り返すパラメータキー</td>
      <td>page</td>
    </tr>
    <tr>
      <td>繰り返す範囲</td>
      <td>1~10</td>
    </tr>
    <tr>
      <td>実行結果</td>
      <td><%= url_tools_image_crawl_url %>?page=1, <%= url_tools_image_crawl_url %>?page=2, ..., <%= url_tools_image_crawl_url %>?page=10</td>
    </tr>
  </tbody>
</table>